---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: example-nats
  namespace: nats-io
spec:
  size: 3
  version: "2.1.7"
  pod:
    enableConfigReload: true
  auth:
    enableServiceAccounts: true

# The ServiceAccount and NatsServiceRole definitions
# are required to have the same name in the namespace.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
  namespace: my-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-user
  namespace: my-ns
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-user
  namespace: nats-io

  # Specifies which NATS cluster will be mapping this account,
  # (have to create a service role with permission per cluster).
  labels:
    nats_cluster: example-nats
spec:
  permissions:
    publish: ["foo.*", "foo.bar.quux"]
    subscribe: ["foo.bar", "greetings", "hello.world"]

---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-admin-user
  namespace: nats-io
  labels:
    nats_cluster: example-nats
spec:
  permissions:
    publish: [">"]
    subscribe: [">"]

---
apiVersion: v1
kind: Pod
metadata:
  name: nats-user-pod
  namespace: my-ns
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - secret:
            name: "nats-user-example-nats-bound-token"
            items:
              - key: token
                path: "token"
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "synadia/nats-box:latest"
      tty: true
      stdin: true
      stdinOnce: true

      # Service Account Token is mounted via projected volume.
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: nats-admin-user-pod
  namespace: my-ns
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - secret:
            name: "nats-admin-user-example-nats-bound-token"
            items:
              - key: token
                path: "token"
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "synadia/nats-box:latest"
      tty: true
      stdin: true
      stdinOnce: true

      # Service Account Token is mounted via projected volume.
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"
        readOnly: true
